-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN     "expirationDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "initialDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "remainingClasses" INTEGER NOT NULL DEFAULT 0;
